### ISSUE TITLE
Incorrect README's usage ?

### ISSUE THREAD

**Issue by uzulla** [moznion/boson#1]
I tried this tool ! but not fire.

```
$ tail -f a |./boson -url "https://notify-api.line.me/api/notify" --header "Content-Type: application/x-www-form-urlencoded" --header "Authorization: Bearer XXX" -body "message=fire"
```

Bellow line worked.

```
$ tail -f a |./boson -url "https://notify-api.line.me/api/notify" --header "Content-Type: application/x-www-form-urlencoded" --header "Authorization: Bearer XXX" --body "message=fire"
```

So, README.md's usage need to be change `-body` `--body`.

thanks!

**Comment by moznion** [comment]
Hmm, it seems weird because the handler of CLI options of this application is golang's [flag](https://golang.org/pkg/flag) package and that deals with flags `-body` and `--body` equally.

Anyway, I'll investigate it. Thank you for the report.

**Comment by uzulla** [comment]
Not work well at own env yet.
but OK, I have a workaround.

thanks for advice!
