### ISSUE TITLE
Feature request,  uri escape function for `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by uzulla** [moznion/boson#2]
If I setup `application/x-www-form-urlencoded` and set `--body` like this....

```
message={{ line }}
```

The result could be that? (when line `LOG&hoge=abc`) 

```
message=LOG&hoge=abc
```

If boson has uri escape(or other escape), will be more usefull.

thanks.

**Comment by moznion** [comment]
Thank you for sharing your idea, it sounds absolutely useful.
I've just implemented that at 0653c95d4e14174f504b8181b65ac9bf98ac095e
